### PR TITLE
Add a new link

### PR DESCRIPTION
**Pull request by johnny5550822**

### CODE REVIEW

**Comment by myungsub** [comment]
Hmm surely there are some categorization issues for those not fitting in perfectly..

**Comment by johnny5550822** [comment]
Ya, maybe we should create new category or something? Or re-organize the links when there are more info?

**Comment by myungsub** [comment]
I think we might need some major reconstruction since there are so many categories to make. We haven't separated many categories especially for NLP and those using attention based models

**Comment by johnny5550822** [comment]
Agree. I would be interested helping that out. Let's me know. :)

**Comment by kjw0612** [comment]
Yeah, I guess we need more recent stuffs. It would be awesome if you give it a try restructuring sections and adding your interests @johnny5550822.

**Comment by johnny5550822** [comment]
Great, thanks for the flexibility. I will try to make suggestions.

**Pull request merged**
