### PR TITLE
New section

### PR DESCRIPTION
**Pull request by johnny5550822**
Create a new section for online examples

### CODE REVIEW

**Comment by johnny5550822** [comment]
What do you think about having a new sectino for online examples. I have seen resources showing real rnn training, etc online. And I think it is cool to include them.

**Comment by myungsub** [comment]
Wouldn't it be better to name the new section as 'Demos'?

**Comment by kjw0612** [comment]
Adding web demos is a very good idea. Are there any other demos you found?

**Comment by johnny5550822** [comment]
Great sounds good to me!

**Comment by johnny5550822** [comment]
@kjw0612  So far I have seen one, but there should be more.

**Pull request merged**
